# Definition of the network policy
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:  
  name: polycubenetworkpolicies.polycube.network
spec:  
  group: polycube.network  
  version: v1beta
  scope: Namespaced
  names:    
    kind: PolycubeNetworkPolicy   
    shortNames: 
    - pnp
    plural: polycubenetworkpolicies
    singular: polycubenetworkpolicy